interface:
  slider: false

machines:
  bodor:
    name: Bodor Laser
    properties:
      maxspeed: 300
      speed: 30
      minpower: 50
      maxpower: 70
      size:
        width: 1220
        height: 900
        show: false
    cut_groups:
      - name:
          de: Holz
          en: Wood
        materials:
          - name:
              de: Sperrholz 4 mm
              en: Plywood 4 mm
            speed: 15
            minpower: 60
            maxpower: 60
          - name:
              de: Sperrholz 6 mm
              en: Plywood 6 mm
            speed: 20
            minpower: 60
            maxpower: 60
    mark_groups:
      - name:
          de: Holz
          en: Wood
        materials:
          - name:
              de: Birke Sperrholz
              en: Birch Plywood
            speed: 1000
            minpower: 8
            maxpower: 25

  thunderlaser:
    name: Thunderlaser
    properties:
      maxspeed: 200
      speed: 30
      minpower: 50
      maxpower: 70
      size:
        width: 900
        height: 600
        show: true
    cut_groups:
      - name:
          de: Holz
          en: Wood
        materials:
          - name:
              de: Birke Sperrholz 3 mm
              en: Birch Plywood 3 mm
            speed: 35
            minpower: 50
            maxpower: 65
          - name:
              de: Birke Sperrholz 4 mm
              en: Birch Plywood 4 mm
            speed: 25
            minpower: 50
            maxpower: 65
          - name:
              de: Birke Sperrholz 5 mm
              en: Birch Plywood 5 mm
            speed: 20
            minpower: 60
            maxpower: 70
      - name:
          de: Kunststoff
          en: Plastics
        materials:
          - name:
              de: Acryl (PMMA) 3 mm
              en: Acrylic (PMMA) 3 mm
            speed: 25
            minpower: 55
            maxpower: 70
          - name:
              de: Acryl (PMMA) 4 mm
              en: Acrylic (PMMA) 4 mm
            speed: 20
            minpower: 55
            maxpower: 70
          - name:
              de: Acryl (PMMA) 5 mm
              en: Acrylic (PMMA) 5 mm
            speed: 15
            minpower: 55
            maxpower: 70
      - name:
          de: Andere
          en: Other
        materials:
          - name:
              de: Karton (FinnP) 1 mm
              en: Cardboard (FinnP) 1 mm
            speed: 300
            minpower: 26
            maxpower: 65
          - name:
              de: Karton (FinnP) 3 mm
              en: Cardboard (FinnP) 3 mm
            speed: 80
            minpower: 50
            maxpower: 70
          - name:
              de: PU Schaum 10 mm
              en: PU foam 10 mm
            speed: 100
            minpower: 50
            maxpower: 70
    mark_groups:
      - name:
          de: Holz
          en: Wood
        materials:
          - name:
              de: Birke Sperrholz
              en: Birch Plywood
            speed: 1000
            minpower: 8
            maxpower: 25
      - name:
          de: Andere
          en: Other
        materials:
          - name:
              de: Karton (Finnpappe)
              en: Cardboard (Finnpappe)
            speed: 1000
            minpower: 7
            maxpower: 18

languages:
  de:
    strings:
      main: allgemein
      cut: schneiden
      mark: markieren
      speed: Geschwindigkeit
      power: Leistung
      minpower: MinLeistung
      maxpower: MaxLeistung
      material: Material
      workspace_width: Breite der Laserfläche
      workspace_height: Höhe der Laserfläche
      linecolor: Wähle Linienfarbe
    colors:
      any: unwichtig
      cut_none: nichts schneiden
      mark_none: nichts markieren
      red: rot
      green: grün
      blue: blau
      black: schwarz
      white: weiß
      cyan: cyan
      magenta: magenta
      yellow: gelb
  en:
    strings:
      main: main
      cut: cut
      mark: mark
      speed: speed
      power: power
      minpower: MinPower
      maxpower: MaxPower
      material: material
      workspace_width: Width of the laser area
      workspace_height: Height of the laser area
      linecolor: By line color
    colors:
      any: any
      cut_none: cut nothing
      mark_none: mark nothing
      red: red
      green: green
      blue: blue
      black: black
      white: white
      cyan: cyan
      magenta: magenta
      yellow: yellow

colors:
  - any
  - none
  - red
  - green
  - blue
  - black
  - white
  - cyan
  - magenta
  - yellow
